### ISSUE TITLE
Feature request source map generation

### ISSUE THREAD

**Issue by timon-schelling** [616slayer616/gradle-minify-plugin#9] opened 2020-04-03 15:09 UTC
I think this gradle plugin is already awesome and easy to use.

But it would be great if it could also take over source map generation for css and javascript.

https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

The configuration could then look like this.
```kotlin
minification {
    jsSrcDir = "$buildDir/minify/src/js"
    jsDstDir = "$buildDir/minify/dst/js"
    cssSrcDir = "$buildDir/minify/src/css"
    cssDstDir = "$buildDir/minify/dst/css"

    jsSourceMaps = true
    cssSourceMaps = true
}
```

Google closure has this feature included. You could just make it usable through this plugin. 
https://github.com/google/closure-compiler/wiki/Source-Maps

**Comment by 616slayer616** [comment] 2020-04-03 15:25
Thanks,

I would love to include more features and make th plugin more usable.
However I have no experience with source maps at all.

I recently included google closure for JS minification but could not get css minification to work.
So generating source maps for JS should not be difficult.
But I'm not sure about the CSS source maps.

Can you help ?

**Comment by timon-schelling** [comment] 2020-04-03 15:38
Yes I can try. What googel closure documentation do you use to get js working?

**Comment by 616slayer616** [comment] 2020-04-03 15:45
I based it off of [gradle-js-plugin](https://github.com/eriwen/gradle-js-plugin/blob/master/src/main/groovy/com/eriwen/gradle/js/JsMinifier.groovy).
He seems to be doing something with source maps aswell.

He uses an older version of closure though.
The new one had many breaking changes.

**Comment by timon-schelling** [comment] 2020-04-03 16:03
Did you considered using google closure to minify css?

Because the YUI Compressor is no longer maintained https://stackoverflow.com/questions/24177065/can-we-generate-sourcemaps-using-yui-compressor

**Comment by 616slayer616** [comment] 2020-04-03 16:25
I have triedd it but could not get it to work.
closure-stylesheets can only be accessed via the command line.
I don't know if the closure-compiler can also minify css

**Comment by timon-schelling** [comment] 2020-04-03 16:42
I guess it is possible to call the closure main function from gradle plugins.
https://github.com/google/closure-stylesheets/blob/970d51e6fb45591e50c057b118e66a364957da42/src/com/google/common/css/compiler/commandline/ClosureCommandLineCompiler.java#L431

It should be possible to just pass all command line arguments in there. And use it like in command line without launching a new jvm.

**Comment by 616slayer616** [comment] 2020-04-03 16:56
Yes that should be possible I tried to call "execute" which is private.

We should try that.

**Comment by 616slayer616** [comment] 2020-04-08 19:46
I got closure-stylesheets to somewhat work:
[](https://github.com/616slayer616/gradle-minify-plugin/tree/closure-stylesheets)

It does not work with my project because of the error "Detected multiple identical, non-alternate declarations in the same ruleset.".

 So closure does not minify these files.

~~The problem is that calling the main method does not print the errors.

Do you have an idea how to achieve this?~~

And do you know how to create the source maps?
As I said I have no experience with them and don't even know what the output should look like.
You should know that better.


Edit: I integrated error handling and I think it might be ready to use.
Maybe you can do something with source maps now.

**Comment by 616slayer616** [comment] 2020-04-09 14:25
I think this is what you want:
[https://github.com/616slayer616/gradle-minify-plugin/commit/6bdbec6c4dd9dc50407797cd320f1e55aba4727d](https://github.com/616slayer616/gradle-minify-plugin/commit/6bdbec6c4dd9dc50407797cd320f1e55aba4727d).

Need to do it for CSS as well but it would be nice if you could give me some feedback about this.

**Comment by timon-schelling** [comment] 2020-04-09 14:34
Sorry for not responding yesterday. 

Thanks. That's it. 

But you might consider implementing the `createJsSourceMaps` as a input property of the minify task.

Like i did with the src and dst dirs. https://github.com/616slayer616/gradle-minify-plugin/blob/7f95d26e8ceb710bafc9800976438953fea97741/src/main/java/org/padler/gradle/minify/MinifyTask.java#L26

But instead of ` @InputDirectory` you would use `@Input` and return it as String.

In this way you can insure that everything gets recompiled with (or without maps) when createJsSourceMaps changed.

**Comment by 616slayer616** [comment] 2020-04-09 14:59
I think I got it:
[https://github.com/616slayer616/gradle-minify-plugin/commit/821e4839445b94f4d2856bc9cc3bf9f053ac3a62](https://github.com/616slayer616/gradle-minify-plugin/commit/821e4839445b94f4d2856bc9cc3bf9f053ac3a62)

I am also enabling renaming files to .min.js and .min.css
[https://github.com/616slayer616/gradle-minify-plugin/commit/6fcf43844fd5ca5efd2089ccfb31fc8578b3851c](https://github.com/616slayer616/gradle-minify-plugin/commit/6fcf43844fd5ca5efd2089ccfb31fc8578b3851c)

What do you think about that?

**Comment by timon-schelling** [comment] 2020-04-10 12:56
Exactly what I mend. 👍 

I and yes renaming to *.min.* is great but i would call the option `originalFileNames`. And I would default it to false because it is kind of a convention in web.

**Comment by timon-schelling** [comment] 2020-04-10 13:03
Do you have a Discord or Skype account?
And you are German right?
Is it possible to have a call with you? I have a idea that is to hard to explain in text.  

I try in https://github.com/616slayer616/gradle-minify-plugin/issues/12

**Comment by 616slayer616** [comment] 2020-04-10 13:13
I don't have discord and haven't logged until Skype for ages.
But yes I'm German and I'm sure we can figure something out for a call.
My first thought is teamspeak.

But I'm moving this weekend so I don't know if I can find the time.
Maybe Monday?

Frohe Ostern

**Comment by timon-schelling** [comment] 2020-04-10 13:32
Thanks and gleichfalls. 
Monday sounds great. 👍 
Do you have a Teamspeak server?

**Comment by 616slayer616** [comment] 2020-04-10 14:03
I have a TS server.
You can reach me for details and to discuss a time for monday via 
patrick@padler.org

**Comment by 616slayer616** [comment] 2020-04-10 14:03
I have implemented something for the CSS source maps

**Comment by timon-schelling** [comment] 2020-04-12 17:01
I have found a issue with js source maps. In map files source files are referenced as a absolute path.
like this
```"sources":["T:/dev/.../build/minify/src/js/lib/chart.js"]```
but it should be only 
```"sources":["chart.js"]```

I guess google closure configuration can fix this.

**Comment by 616slayer616** [comment] 2020-04-12 17:55
I could fix this but the problem is files in sub directories would lose the sub directory .
That happens in the css source maps though so it would at least be consistent

**Comment by timon-schelling** [comment] 2020-04-12 18:02
I think you misunderstand what I mend. We should speak about this tomorrow.

**Closed as completed** 2020-04-14 13:17 UTC
Labels: enhancement
